### ISSUE TITLE
Heya, Compile Errors

### ISSUE THREAD

**Issue by jevilhumor** [Animelici804/Undertale-Engine#1]
When loading up da game, this happens.
![20190902_113730](https://user-images.githubusercontent.com/54338841/64087020-28737100-cd76-11e9-86fd-84b093cc4e26.gif)

**Comment by jevilhumor** [comment]
What's wrong?

**Comment by Animeliqite** [comment]
You must be running the old version of GMS 1.4. You should update it to get it to work.
